# duration = 6			# time, in seconds, between image transitions
# img_directory = "."		# path to a folder containing image files (.jpg and .png only)
# image_save_path = '.'	# directory path for saving selected photos
# topmost = False		# boolean flag to set whether the slideshow is displayed on top of all other windows or not
# size_max_x = 96		# maxiumum size, in pixels, to display the image at in the horizontal (x) direction
# size_max_y = 96		# maxiumum size, in pixels, to display the image at in the vertical (y) direction
# position_x = 0		# starting horizontal position, in pixels, from which the image is displayed relative to the top-left corner of the display, (0, 0)
# position_y = 0		# starting vertical position, in pixels, from which the image is displayed relative to the top-left corner of the display, (0, 0)
# fullscreen = True		# flag to indicate whether the slideshow should take up the full screen with black background
# montage_mode = True	# flag to indicate if montage mode is activated (several tiled images)
# montage_size = 10		# number of photos to use in each montage when montage mode is activated
video_player_enable = True	# flag to indicate if the slideshow is in video mode